# Generated by Django 4.2.6 on 2023-10-26 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_shoppinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddresOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=150)),
                ('PhoneNumber', models.CharField(verbose_name=25)),
                ('EmailAddres', models.CharField(max_length=150)),
                ('Country', models.CharField(max_length=150)),
                ('AddressLine1', models.CharField(max_length=150)),
                ('AddressLine2', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=150)),
                ('District', models.CharField(max_length=150)),
                ('Postcode', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shoppinghistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
