# Generated by Django 4.2.6 on 2023-10-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_deliveryaddresofuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddresofuser',
            name='ShippingDetails',
            field=models.TextField(default=0, max_length=500),
        ),
    ]
