# Generated by Django 4.2.6 on 2023-10-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userblogcomments_blogphotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogphotos',
            name='user_comment',
        ),
        migrations.AddField(
            model_name='blogphotos',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userblogcomments'),
        ),
    ]
