# Generated by Django 4.2.6 on 2023-10-27 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_user_userblogcomments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblogcomments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
