# Generated by Django 4.2.6 on 2023-10-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userblogcomments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddresofuser',
            name='order',
        ),
    ]
